---
- name: configuring service with handler
  hosts: all
  tasks:
    - name: Edit ssh configuration
      blockinfile:
        path: /etc/ssh/sshd_config
        block: | 
          MaxAuthTries 4
          Banner /etc/motd
          X11Forwarding no
      notify: restart ssh
      
  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted