---
- name: working with variables
  hosts: all
  vars_file: var_example_file.yml
  tasks:
    - name: show port number listed in var_example_file
      debug:
        msg: show item as normal like above task: {{ port_num[3]}