---
- name: handling failure with block v2
  hosts: all
  tasks:
    - name: Handling error example v2
      block:
        - name: normal command
          command: uptime
        - name: bad task
          command: blabla
          ignore_errors: yes
        - name: This will run
          debug:
            msg: "I run since above task error was ignored"
      rescue:
        - name: This will not run
          debug:
            msg: "Error was ignored!... not going to run"