---
- name: loop control playbook
  hosts: all
  tasks:
    - name: countdown happy birthday
      debug:
        msg: "{{ 10 - item }} second remaing..."
      loop: "{{ range(10) | list }}"
      loop_control:
        pause: 1
    
    - name: Display Happy Birthday
      debug:
        msg: Happy Birthday