---
- name: looping over inventory
  hosts: all
  tasks:
    - name: Ping all hosts in inventory file
      command: ping -c 1 {{ items }}
      loop:  "{{ groups['all'] }}"

    - name: Ping specific hosts in inventory file
      command: ping -c 2 {{ items }}
      loop: "{{ groups['dbserver'] }}"