---
- name: When and variable
  hosts: all
  vars:
    weekend: true
    oncall: "no"
  tasks:
    - name: play1
      debug:
        msg: "You are free!"
      when: weekend and not oncall | bool
      